# Generated by Django 5.0.3 on 2025-02-20 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.URLField()),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.PositiveIntegerField()),
                ('depart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('depart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('u_roll', models.IntegerField(default=56, primary_key=True, serialize=False)),
                ('c_roll', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=30)),
                ('batch', models.CharField(max_length=15)),
                ('sec', models.CharField(max_length=10, null=True)),
                ('sec_group', models.CharField(max_length=5, null=True)),
                ('course', models.CharField(max_length=15)),
                ('father_name', models.CharField(max_length=30)),
                ('mother_name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('image', models.URLField()),
                ('password', models.CharField(default='123', max_length=10)),
                ('sem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id', models.CharField(max_length=10, null=True, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10, null=True)),
                ('depart_sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('is_present', models.CharField(max_length=2)),
                ('u_roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.students')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAlott',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.day')),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employees')),
                ('sec', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.sections')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subjects')),
            ],
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('depart_id', 'sem'), name='unique_department_sem'),
        ),
        migrations.AddConstraint(
            model_name='sections',
            constraint=models.UniqueConstraint(fields=('depart_id', 'section'), name='unique_department_section'),
        ),
    ]
