# Generated by Django 5.0.3 on 2025-06-16 07:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dId', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=20)),
                ('experties', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.URLField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeess', to='api.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeess', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.PositiveIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='api.department')),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.department')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_roll', models.IntegerField(blank=True, null=True, unique=True)),
                ('c_roll', models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator('[A-Za-z0-9]', 'Enter c_roll (only alphanumeric is alowed)')])),
                ('name', models.CharField(max_length=35)),
                ('batch', models.CharField(max_length=20)),
                ('sec_group', models.CharField(max_length=5)),
                ('course', models.CharField(max_length=15)),
                ('father_name', models.CharField(max_length=30)),
                ('mother_name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9._+-]+@gmail\\.com$', 'Enter gmail (@gmail.com)')])),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter only 10 digits number.')])),
                ('father_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter only 10 digits number-')])),
                ('image', models.URLField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.department')),
                ('sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.sections')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.semester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id', models.CharField(max_length=10, null=True, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='api.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='api.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('is_present', models.CharField(max_length=2)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendences', to='api.department')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendences', to='api.group')),
                ('sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendences', to='api.sections')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendences', to='api.students')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendences', to='api.subjects')),
            ],
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('department', 'sem'), name='unique_department_sem'),
        ),
        migrations.AddConstraint(
            model_name='sections',
            constraint=models.UniqueConstraint(fields=('department', 'section'), name='unique_department_section'),
        ),
        migrations.AddConstraint(
            model_name='subjects',
            constraint=models.UniqueConstraint(fields=('department', 'semester', 'sub_id'), name='unique_dep_sem_sub_id'),
        ),
    ]
