# Generated by Django 5.0.3 on 2025-06-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sections',
            name='unique_department_section',
        ),
        migrations.AddConstraint(
            model_name='sections',
            constraint=models.UniqueConstraint(fields=('department', 'semester', 'section', 'group'), name='unique_department_section'),
        ),
    ]
