# Generated by Django 5.0.3 on 2025-06-17 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_sections_unique_department_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='sec_group',
        ),
        migrations.AddField(
            model_name='students',
            name='group',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.group'),
        ),
    ]
