# Generated by Django 5.0.3 on 2025-06-17 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_students_sec_group_students_group'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sections',
            name='unique_department_section',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='sections',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.sections'),
        ),
        migrations.AddConstraint(
            model_name='sections',
            constraint=models.UniqueConstraint(fields=('department', 'semester', 'section'), name='unique_department_section'),
        ),
    ]
