# Generated by Django 5.0.3 on 2025-07-02 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_employee_department_alter_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAlott',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.day')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
        ),
       
    ]
