# Generated by Django 5.0.3 on 2025-07-02 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_teacheralott_teacheralott_check_teacher_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('lab', 'LAB'), ('tute', 'Tute')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teacheralott',
            name='time',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(0[1-9]|1[0-2]):[0-5][0-9]\\s?(AM|PM)-(0[1-9]|1[0-2]):[0-5][0-9]\\s?(AM|PM)$', 'HH:MM AM/PM-HH:MM AM/PM')]),
        ),
    ]
