# Generated by Django 5.0.3 on 2025-07-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_subject_type_alter_teacheralott_time'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teacheralott',
            constraint=models.UniqueConstraint(fields=('employees', 'section', 'subject', 'day'), name='unique teacher can teach unique subject each day'),
        ),
    ]
