# Generated by Django 5.0.3 on 2025-07-02 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_teacheralott_unique_teacher_can_teach_unique_subject_each_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheralott',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacherallot', to='api.group'),
        ),
        migrations.AlterField(
            model_name='teacheralott',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherallot', to='api.day'),
        ),
        migrations.AlterField(
            model_name='teacheralott',
            name='employees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherallot', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='teacheralott',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherallot', to='api.section'),
        ),
        migrations.AlterField(
            model_name='teacheralott',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherallot', to='api.subject'),
        ),
    ]
