# Generated by Django 5.0.3 on 2025-07-02 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_teacheralott_group_alter_teacheralott_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheralott',
            name='group',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherallot', to='api.group'),
        ),
    ]
