# Generated by Django 5.0.3 on 2025-07-02 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_teacheralott_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheralott',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherallot', to='api.group'),
        ),
    ]
