# Generated by Django 5.0.3 on 2025-07-02 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_teacheralott_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendence', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendence', to='api.department'),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendence', to='api.group'),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='sections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendence', to='api.section'),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendence', to='api.student'),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendence', to='api.subject'),
        ),
    ]
