# Generated by Django 5.0.3 on 2025-07-02 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_attendence_employee_alter_attendence_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendence', to='api.employee'),
        ),
    ]
