# Generated by Django 5.0.3 on 2025-07-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_attendence_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
