# Generated by Django 5.0.3 on 2025-07-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_attendence_is_present'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique_dep_sem_sub_id',
        ),
        migrations.AlterField(
            model_name='day',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('student', 'Student'), ('faculty', 'Faculty')], max_length=15),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('department', 'semester', 'sub_id', 'type'), name='unique_dep_sem_sub_id'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('sub_id', 'type'), name='unique_sub'),
        ),
    ]
