# Generated by Django 5.0.3 on 2025-07-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_subject_unique_dep_sem_sub_id_alter_day_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
