# Generated by Django 5.0.3 on 2025-07-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_subject_name_alter_subject_sub_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacheralott',
            name='unique teacher can teach unique subject each day',
        ),
        migrations.AddConstraint(
            model_name='teacheralott',
            constraint=models.UniqueConstraint(fields=('employees', 'section', 'subject', 'group', 'day'), name='unique teacher can teach unique subject each day'),
        ),
    ]
