# Generated by Django 5.0.3 on 2025-07-28 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_teacheralott_unique_teacher_can_teach_unique_subject_each_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaddate', models.DateField(auto_now_add=True)),
                ('assignmentfile', models.FileField(upload_to='assignments/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academicassignment', to='api.department')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academicassignment', to='api.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academicassignment', to='api.semester')),
            ],
        ),
        migrations.CreateModel(
            name='TableHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logfile', models.FileField(upload_to='logs/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablehistory', to='api.department')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablehistory', to='api.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablehistory', to='api.semester')),
            ],
        ),
    ]
