# Generated by Django 5.0.3 on 2025-07-29 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_academicassignment_tablehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicassignment',
            name='employee',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='academicassignment', to='api.employee'),
        ),
    ]
