# Generated by Django 5.0.3 on 2025-07-29 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_academicassignment_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academicassignment', to='api.employee'),
        ),
    ]
