# Generated by Django 5.0.3 on 2025-07-29 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_academicassignment_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicassignment',
            name='subject',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='academicassignment', to='api.subject'),
        ),
    ]
